server:
  port: 8063

spring:
  datasource:
    url: jdbc:h2:mem:authDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /console

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

jwtconfig:
  secret: the_secret
  token-validity-in-seconds: 250000

security:
  ignored:
    - none