server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
  routes:
    authentication:
      path: /authentication/**
      serviceId: authentication
      sensitiveHeaders:
    projet:
      path: /projet/**
      serviceId: projet
    payment:
      path: /payment/**
      serviceId: payment
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

